# -*- coding: utf-8 -*-
"""Mastering Python Again.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16k5h0yetk4ok0rW4tw3PtRcnh2jbEnDH

#**CONTROL FLOW**
#*Round Function*
"""

print(round(4.55))

print(round(6.6))

"""#*Rounds with Arguments*"""

print(round(5.443434, 4))

"""#*Divmod*"""

divmod(22, 10)

divmod(34, 9)

"""#*isinstance*"""

isinstance(4, int)

isinstance(5.6, float)

"""#*Power*"""

pow(2,4)

pow(2,4,2)

"""#*If and Else Condition*"""

A = 5
B = 19
if A>B:
  print("A is bigger than B")
else:
    print("B is bigger than A")

"""#*A bit complex*"""

A = float(input("Enter a number : "))
B = float(input("Enter a second number : "))
if A>B:
  print("A is bigger than B")
elif A==B:
  print("They are equal")
else:
  print("B is bigger than A")

"""#*While loop*"""

n = int(input("Enter a number : "))
i = 1
while i < n:
  print(i**2)
  print("This is a iteration number :", i)
  i += 1
print("Loop done!")

"""#*Continous and break Loop*"""

n = 10
i = 1
while True:
  if i%9 != 0:
    print("Inside if")
    i += 1
    continue
  print("something")
  print("something else")
  break

print("done")

"""#*For loop*"""

L = []
for i in range(5,100,5):
   print(i)
   L.append(i**2)
print(L)

"""#*Else in for loop*"""

S = { "Apple","Ball","9.4","Security"}
for x in S:
  print(x)
else:
     print("Loop terminated with success")
print("Finished")

"""#*A bit complex ELSE in FOR LOOP*"""

S = {"Apple","Ball","9.4","Security"}
i = 1
for x in S:
  print(x)
  i += 1
  if i == 3:
    break
  else:
    pass
else:
     print("Loop terminated with success")
print("Finished")

"""#*Exploring a dictionary*"""

D = {"A":23, "B":64, "C":45}
for x in D:
  print(x, D[x])

"""#*Knowing minimum value and index in a list*"""

L = [1, 2, 3, 5, 20, 50, -5, -3, 85]

m = L[0]
ind = 0
c = 0
for i in L:
  if i<m:
    m = i
    ind = c
  c+=1

print(ind, m)

"""#*Sorting numbers from minimum to max*"""

L = [1, 2, 3, 5, -5, -3]
for j in range(len(L)):
    m = L[0]
    ind = 0
    c = j
    for i in range(j,len(L)):
        if L[i]<m:
            m = L[i]
            ind = c
        c += 1
    tem = L[j]
    L[j] = m
    L[ind] = tem  
print(L)

"""#**Functions**"""

def mypow(a, b):
  """This computes the power"""
  c = a**b
  print(c)
mypow(3, 4)

def checkArguments(a, b, c):
  if isinstance(a,(int,float )) and isinstance(b,(int,float)) and isinstance(c,(int,float)):
      print((a+b+c)**2)
  else:
    print("Error")
checkArguments(3, 4, 5)

def f(a,b,c):
  print("A is :",a)
  print("B is :",b)
  print("C is :",c)
f(2, 3, "Not nice, fucker")

"""#*Return statement*"""

def myadd(a, b):
  c = a+b
  return c
d = myadd(4, 5)
print(d)

def r():
  a = 1
  b = 2
  d = "something"
  return a,b,d
x,y,z = r()  
print(x,y,z)

def add(*args):
  s = 0
  for i in range(len(args)):
    s += args[i]  # s = s+args[i]
  return s 
print(add(2, 4, 9, 12.6))